import { Express } from "express";
import authRoutes from "./auth";
import userRoutes from "./user";
import classRoutes from "./class";
import aiRoutes from "./ai";
import recommendRoutes from "./recommend";
import radarRoutes from "./radar";
import analysisRoutes from "./analysis";
import detailedProfileRoutes from "./detailedProfile";
import contestRoutes from "./contests";
import companyRoutes from "./companies";
import collegeRoutes from "./college";
import courseRoutes from "./course";
import joinRequestRoutes from "./joinRequest";
import adminRoutes from "./admin";
import dsaPracticeRoutes from "./dsaPractice";
import contestHistoryRoutes from "./contestHistory";
import savedContestRoutes from "./savedContests";
import hackathonRoutes from "./hackathons";
import postRoutes from "./posts";
import profileRoutes from "./profiles";
import metricsRoutes from "./metrics";
import dailyProblemRoutes from "./dailyProblem";
import leaderboardRoutes from "./leaderboard";
import classAssignmentRoutes from "./classAssignment";
import maintenanceRoutes from "./maintenance";

export function registerRoutes(app: Express) {
  app.use("/api/auth", authRoutes);
  app.use("/api/user", userRoutes);
  app.use("/api/class", classRoutes);
  app.use("/api/ai", aiRoutes);
  app.use("/api/recommend", recommendRoutes);
  app.use("/api/radar", radarRoutes);
  app.use("/api/analysis", analysisRoutes);
  app.use("/api", detailedProfileRoutes);
  app.use("/api/contests", contestRoutes);
  app.use("/api/companies", companyRoutes);
  app.use("/api/colleges", collegeRoutes);
  app.use("/api", courseRoutes);
  app.use("/api/join-requests", joinRequestRoutes);
  app.use("/api/admin", adminRoutes);
  app.use("/api/admin", maintenanceRoutes);
  app.use("/api/dsa-practice", dsaPracticeRoutes);
  app.use("/api/contest-history", contestHistoryRoutes);
  app.use("/api/contests/saved", savedContestRoutes);
  app.use("/api/hackathons", hackathonRoutes);
  app.use("/api/posts", postRoutes);
  app.use("/api/profiles", profileRoutes);
  app.use("/api", metricsRoutes);
  app.use("/api", dailyProblemRoutes);
  app.use("/api", leaderboardRoutes);
  app.use("/api", classAssignmentRoutes);
}
